services:
  db-dev:
    image: postgres:16-alpine
    container_name: saasfoundry-db-dev
    restart: 'no' # No need for auto-restart for dev tests
    environment:
      POSTGRES_USER: db_dev_user
      POSTGRES_PASSWORD: db_dev_password
      POSTGRES_DB: db_dev
      # Config optimized for dev tests
      POSTGRES_INITDB_ARGS: '--nosync'
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRESQL_SHARED_BUFFERS: 128MB
      POSTGRESQL_EFFECTIVE_CACHE_SIZE: 384MB
      POSTGRESQL_MAINTENANCE_WORK_MEM: 64MB
      POSTGRESQL_CHECKPOINT_COMPLETION_TARGET: 0.7
      POSTGRESQL_MAX_WAL_SIZE: 1GB
      POSTGRESQL_MIN_WAL_SIZE: 80MB
    command: >
      postgres -c shared_buffers=128MB -c effective_cache_size=384MB -c maintenance_work_mem=64MB -c checkpoint_completion_target=0.7 -c max_wal_size=1GB -c min_wal_size=80MB -c fsync=off -c
      synchronous_commit=off -c full_page_writes=off
    ports:
      - '5435:5432'
    tmpfs:
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=500m # Use tmpfs instead of a volume
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U db_dev_user -d db_dev']
      interval: 5s
      retries: 5
      start_period: 5s
    networks:
      - saasfoundry-network

volumes:
  db-dev-data:
    driver: local

networks:
  saasfoundry-network:
    external: true
